// 초등학교 3~6학년 필수 영단어 데이터
// 각 항목: [영단어, 뜻, 품사, 예문(영), 예문(한), 카테고리]

export type WordTuple = [string, string, string, string, string, string];

export interface WordSeed {
  text: string;
  meaning: string;
  partOfSpeech: string;
  exampleEn: string;
  exampleKo: string;
  grade: number;
  category: string;
}

const GRADE_3: WordTuple[] = [
  // 숫자
  ["one", "하나, 1", "수사", "I have one apple.", "나는 사과 한 개를 가지고 있어요.", "숫자"],
  ["two", "둘, 2", "수사", "I have two dogs.", "나는 개 두 마리를 가지고 있어요.", "숫자"],
  ["three", "셋, 3", "수사", "There are three books.", "책이 세 권 있어요.", "숫자"],
  ["four", "넷, 4", "수사", "She has four pencils.", "그녀는 연필 네 자루를 가지고 있어요.", "숫자"],
  ["five", "다섯, 5", "수사", "I see five birds.", "나는 새 다섯 마리를 봐요.", "숫자"],
  ["six", "여섯, 6", "수사", "He is six years old.", "그는 여섯 살이에요.", "숫자"],
  ["seven", "일곱, 7", "수사", "There are seven days in a week.", "일주일은 칠 일이에요.", "숫자"],
  ["eight", "여덟, 8", "수사", "It is eight o'clock.", "여덟 시예요.", "숫자"],
  ["nine", "아홉, 9", "수사", "I have nine crayons.", "나는 크레용 아홉 개를 가지고 있어요.", "숫자"],
  ["ten", "열, 10", "수사", "Count to ten.", "열까지 세어보세요.", "숫자"],
  // 색깔
  ["red", "빨간색", "형용사", "The apple is red.", "사과가 빨간색이에요.", "색깔"],
  ["blue", "파란색", "형용사", "The sky is blue.", "하늘이 파란색이에요.", "색깔"],
  ["yellow", "노란색", "형용사", "I like the yellow flower.", "나는 노란 꽃을 좋아해요.", "색깔"],
  ["green", "초록색", "형용사", "The leaf is green.", "나뭇잎이 초록색이에요.", "색깔"],
  ["black", "검은색", "형용사", "My cat is black.", "내 고양이는 검은색이에요.", "색깔"],
  ["white", "흰색", "형용사", "Snow is white.", "눈은 흰색이에요.", "색깔"],
  ["orange", "주황색", "형용사", "I have an orange bag.", "나는 주황색 가방이 있어요.", "색깔"],
  ["pink", "분홍색", "형용사", "She wears a pink dress.", "그녀는 분홍색 드레스를 입어요.", "색깔"],
  ["purple", "보라색", "형용사", "The grapes are purple.", "포도는 보라색이에요.", "색깔"],
  ["brown", "갈색", "형용사", "The bear is brown.", "곰은 갈색이에요.", "색깔"],
  // 가족
  ["mother", "어머니", "명사", "My mother is kind.", "우리 어머니는 친절하세요.", "가족"],
  ["father", "아버지", "명사", "My father works hard.", "우리 아버지는 열심히 일하세요.", "가족"],
  ["sister", "언니, 누나, 여동생", "명사", "I have one sister.", "나는 여자 형제가 한 명 있어요.", "가족"],
  ["brother", "형, 오빠, 남동생", "명사", "My brother is tall.", "우리 오빠는 키가 커요.", "가족"],
  ["grandmother", "할머니", "명사", "I love my grandmother.", "나는 할머니를 사랑해요.", "가족"],
  ["grandfather", "할아버지", "명사", "My grandfather tells great stories.", "할아버지는 멋진 이야기를 해주세요.", "가족"],
  ["baby", "아기", "명사", "The baby is sleeping.", "아기가 자고 있어요.", "가족"],
  ["family", "가족", "명사", "I love my family.", "나는 우리 가족을 사랑해요.", "가족"],
  ["aunt", "이모, 고모", "명사", "My aunt lives in Seoul.", "우리 이모는 서울에 사세요.", "가족"],
  ["uncle", "삼촌, 이모부", "명사", "My uncle has a big car.", "우리 삼촌은 큰 차가 있어요.", "가족"],
  // 동물
  ["dog", "개", "명사", "The dog runs fast.", "그 개는 빨리 달려요.", "동물"],
  ["cat", "고양이", "명사", "The cat is sleeping.", "고양이가 자고 있어요.", "동물"],
  ["bird", "새", "명사", "A bird is singing.", "새가 노래하고 있어요.", "동물"],
  ["fish", "물고기", "명사", "The fish swims in the water.", "물고기가 물속에서 헤엄쳐요.", "동물"],
  ["lion", "사자", "명사", "The lion is strong.", "사자는 힘이 세요.", "동물"],
  ["tiger", "호랑이", "명사", "The tiger runs fast.", "호랑이는 빨리 달려요.", "동물"],
  ["elephant", "코끼리", "명사", "The elephant is big.", "코끼리는 커요.", "동물"],
  ["rabbit", "토끼", "명사", "The rabbit jumps high.", "토끼는 높이 뛰어요.", "동물"],
  ["bear", "곰", "명사", "The bear likes honey.", "곰은 꿀을 좋아해요.", "동물"],
  ["monkey", "원숭이", "명사", "The monkey climbs the tree.", "원숭이가 나무를 올라가요.", "동물"],
  // 학용품/학교
  ["school", "학교", "명사", "I go to school every day.", "나는 매일 학교에 가요.", "학용품/학교"],
  ["teacher", "선생님", "명사", "My teacher is nice.", "우리 선생님은 친절하세요.", "학용품/학교"],
  ["student", "학생", "명사", "I am a student.", "나는 학생이에요.", "학용품/학교"],
  ["book", "책", "명사", "I read a book.", "나는 책을 읽어요.", "학용품/학교"],
  ["pencil", "연필", "명사", "This is my pencil.", "이것은 내 연필이에요.", "학용품/학교"],
  ["eraser", "지우개", "명사", "Can I use your eraser?", "네 지우개 써도 될까?", "학용품/학교"],
  ["desk", "책상", "명사", "The book is on the desk.", "책이 책상 위에 있어요.", "학용품/학교"],
  ["chair", "의자", "명사", "Sit on the chair.", "의자에 앉으세요.", "학용품/학교"],
  ["bag", "가방", "명사", "My bag is heavy.", "내 가방은 무거워요.", "학용품/학교"],
  ["notebook", "공책", "명사", "I write in my notebook.", "나는 공책에 써요.", "학용품/학교"],
  // 신체
  ["head", "머리", "명사", "My head hurts.", "머리가 아파요.", "신체"],
  ["eye", "눈", "명사", "I have two eyes.", "나는 눈이 두 개 있어요.", "신체"],
  ["nose", "코", "명사", "My nose is small.", "내 코는 작아요.", "신체"],
  ["mouth", "입", "명사", "Open your mouth.", "입을 벌리세요.", "신체"],
  ["ear", "귀", "명사", "I have two ears.", "나는 귀가 두 개 있어요.", "신체"],
  ["hand", "손", "명사", "Wash your hands.", "손을 씻으세요.", "신체"],
  ["foot", "발", "명사", "My foot is big.", "내 발은 커요.", "신체"],
  ["arm", "팔", "명사", "I hurt my arm.", "나는 팔을 다쳤어요.", "신체"],
  ["leg", "다리", "명사", "My legs are tired.", "다리가 피곤해요.", "신체"],
  ["hair", "머리카락", "명사", "Her hair is long.", "그녀의 머리카락은 길어요.", "신체"],
  // 음식
  ["apple", "사과", "명사", "I eat an apple every day.", "나는 매일 사과를 먹어요.", "음식"],
  ["banana", "바나나", "명사", "The monkey eats a banana.", "원숭이가 바나나를 먹어요.", "음식"],
  ["milk", "우유", "명사", "I drink milk in the morning.", "나는 아침에 우유를 마셔요.", "음식"],
  ["bread", "빵", "명사", "I like fresh bread.", "나는 신선한 빵을 좋아해요.", "음식"],
  ["rice", "쌀, 밥", "명사", "We eat rice for lunch.", "우리는 점심에 밥을 먹어요.", "음식"],
  ["egg", "달걀", "명사", "I eat an egg for breakfast.", "나는 아침으로 달걀을 먹어요.", "음식"],
  ["water", "물", "명사", "Please drink some water.", "물을 좀 마시세요.", "음식"],
  ["juice", "주스", "명사", "I like orange juice.", "나는 오렌지 주스를 좋아해요.", "음식"],
  ["cake", "케이크", "명사", "We have cake on my birthday.", "내 생일에 케이크를 먹어요.", "음식"],
  ["cookie", "쿠키", "명사", "Mom baked cookies.", "엄마가 쿠키를 구워주셨어요.", "음식"],
  // 요일
  ["Monday", "월요일", "명사", "I have math class on Monday.", "나는 월요일에 수학 수업이 있어요.", "요일"],
  ["Tuesday", "화요일", "명사", "We play soccer on Tuesday.", "우리는 화요일에 축구를 해요.", "요일"],
  ["Wednesday", "수요일", "명사", "I visit my grandma on Wednesday.", "나는 수요일에 할머니 댁에 가요.", "요일"],
  ["Thursday", "목요일", "명사", "I have art class on Thursday.", "나는 목요일에 미술 수업이 있어요.", "요일"],
  ["Friday", "금요일", "명사", "I like Friday the best.", "나는 금요일을 제일 좋아해요.", "요일"],
  ["Saturday", "토요일", "명사", "We go to the park on Saturday.", "우리는 토요일에 공원에 가요.", "요일"],
  ["Sunday", "일요일", "명사", "I rest on Sunday.", "나는 일요일에 쉬어요.", "요일"],
  ["today", "오늘", "명사", "Today is Monday.", "오늘은 월요일이에요.", "요일"],
  ["tomorrow", "내일", "명사", "See you tomorrow.", "내일 봐요.", "요일"],
  ["yesterday", "어제", "명사", "It rained yesterday.", "어제 비가 왔어요.", "요일"],
  // 기본동사
  ["go", "가다", "동사", "I go to school by bus.", "나는 버스를 타고 학교에 가요.", "기본동사"],
  ["come", "오다", "동사", "Please come here.", "이리 오세요.", "기본동사"],
  ["eat", "먹다", "동사", "I eat breakfast at seven.", "나는 일곱 시에 아침을 먹어요.", "기본동사"],
  ["drink", "마시다", "동사", "I drink water every day.", "나는 매일 물을 마셔요.", "기본동사"],
  ["sleep", "자다", "동사", "I sleep at nine.", "나는 아홉 시에 자요.", "기본동사"],
  ["run", "달리다", "동사", "The dog can run fast.", "그 개는 빨리 달릴 수 있어요.", "기본동사"],
  ["jump", "뛰다, 점프하다", "동사", "The rabbit can jump high.", "토끼는 높이 뛸 수 있어요.", "기본동사"],
  ["walk", "걷다", "동사", "I walk to school.", "나는 학교까지 걸어가요.", "기본동사"],
  ["sit", "앉다", "동사", "Please sit down.", "앉아 주세요.", "기본동사"],
  ["stand", "서다", "동사", "Please stand up.", "일어서 주세요.", "기본동사"],
  // 인사/기초표현
  ["hello", "안녕", "감탄사", "Hello, how are you?", "안녕, 잘 지내니?", "인사/기초표현"],
  ["bye", "안녕(작별)", "감탄사", "Bye! See you later.", "안녕! 나중에 봐.", "인사/기초표현"],
  ["yes", "네, 응", "부사", "Yes, I like it.", "네, 저는 그것을 좋아해요.", "인사/기초표현"],
  ["no", "아니오", "부사", "No, thank you.", "아니오, 괜찮아요.", "인사/기초표현"],
  ["friend", "친구", "명사", "She is my best friend.", "그녀는 내 가장 친한 친구예요.", "인사/기초표현"],
  ["name", "이름", "명사", "My name is Jihoo.", "제 이름은 지후예요.", "인사/기초표현"],
  ["happy", "행복한", "형용사", "I am happy today.", "나는 오늘 행복해요.", "인사/기초표현"],
  ["sad", "슬픈", "형용사", "She looks sad.", "그녀는 슬퍼 보여요.", "인사/기초표현"],
  ["big", "큰", "형용사", "The elephant is big.", "코끼리는 커요.", "인사/기초표현"],
  ["small", "작은", "형용사", "The mouse is small.", "쥐는 작아요.", "인사/기초표현"],
];

const GRADE_4: WordTuple[] = [
  // 학교생활
  ["classroom", "교실", "명사", "Our classroom is bright.", "우리 교실은 밝아요.", "학교생활"],
  ["homework", "숙제", "명사", "I do my homework after school.", "나는 방과 후에 숙제를 해요.", "학교생활"],
  ["test", "시험", "명사", "We have a test tomorrow.", "우리는 내일 시험이 있어요.", "학교생활"],
  ["lesson", "수업", "명사", "Today's lesson is fun.", "오늘 수업은 재미있어요.", "학교생활"],
  ["subject", "과목", "명사", "Math is my favorite subject.", "수학은 내가 가장 좋아하는 과목이에요.", "학교생활"],
  ["math", "수학", "명사", "I like math class.", "나는 수학 수업을 좋아해요.", "학교생활"],
  ["science", "과학", "명사", "Science class is exciting.", "과학 수업은 흥미진진해요.", "학교생활"],
  ["music", "음악", "명사", "We sing songs in music class.", "우리는 음악 수업에서 노래를 불러요.", "학교생활"],
  ["art", "미술", "명사", "I draw pictures in art class.", "나는 미술 시간에 그림을 그려요.", "학교생활"],
  ["gym", "체육관", "명사", "We play games in the gym.", "우리는 체육관에서 게임을 해요.", "학교생활"],
  // 날씨
  ["sunny", "화창한, 맑은", "형용사", "It is sunny today.", "오늘은 날씨가 맑아요.", "날씨"],
  ["rainy", "비가 오는", "형용사", "It is rainy outside.", "밖에 비가 와요.", "날씨"],
  ["cloudy", "흐린", "형용사", "It is cloudy today.", "오늘은 날씨가 흐려요.", "날씨"],
  ["snowy", "눈이 오는", "형용사", "It is snowy in winter.", "겨울에는 눈이 와요.", "날씨"],
  ["windy", "바람이 부는", "형용사", "It is very windy today.", "오늘은 바람이 많이 불어요.", "날씨"],
  ["hot", "더운", "형용사", "It is hot in summer.", "여름에는 더워요.", "날씨"],
  ["cold", "추운", "형용사", "It is cold in winter.", "겨울에는 추워요.", "날씨"],
  ["warm", "따뜻한", "형용사", "The soup is warm.", "그 수프는 따뜻해요.", "날씨"],
  ["cool", "시원한", "형용사", "The weather is cool today.", "오늘 날씨는 시원해요.", "날씨"],
  ["weather", "날씨", "명사", "How is the weather today?", "오늘 날씨는 어때요?", "날씨"],
  // 계절/시간
  ["spring", "봄", "명사", "Flowers bloom in spring.", "봄에는 꽃이 피어요.", "계절/시간"],
  ["summer", "여름", "명사", "I swim in summer.", "나는 여름에 수영을 해요.", "계절/시간"],
  ["fall", "가을", "명사", "Leaves fall in fall.", "가을에는 낙엽이 져요.", "계절/시간"],
  ["winter", "겨울", "명사", "We build snowmen in winter.", "우리는 겨울에 눈사람을 만들어요.", "계절/시간"],
  ["morning", "아침", "명사", "I exercise in the morning.", "나는 아침에 운동을 해요.", "계절/시간"],
  ["noon", "정오", "명사", "We eat lunch at noon.", "우리는 정오에 점심을 먹어요.", "계절/시간"],
  ["afternoon", "오후", "명사", "I study in the afternoon.", "나는 오후에 공부해요.", "계절/시간"],
  ["evening", "저녁", "명사", "We eat dinner in the evening.", "우리는 저녁에 저녁밥을 먹어요.", "계절/시간"],
  ["night", "밤", "명사", "I sleep at night.", "나는 밤에 자요.", "계절/시간"],
  ["week", "주, 일주일", "명사", "I have piano lessons once a week.", "나는 일주일에 한 번 피아노 수업을 받아요.", "계절/시간"],
  // 장소
  ["park", "공원", "명사", "We play in the park.", "우리는 공원에서 놀아요.", "장소"],
  ["zoo", "동물원", "명사", "We saw lions at the zoo.", "우리는 동물원에서 사자를 봤어요.", "장소"],
  ["museum", "박물관", "명사", "We visited a museum.", "우리는 박물관을 방문했어요.", "장소"],
  ["library", "도서관", "명사", "I read books at the library.", "나는 도서관에서 책을 읽어요.", "장소"],
  ["hospital", "병원", "명사", "My mom works at a hospital.", "우리 엄마는 병원에서 일하세요.", "장소"],
  ["market", "시장", "명사", "We buy fruit at the market.", "우리는 시장에서 과일을 사요.", "장소"],
  ["restaurant", "식당", "명사", "We ate dinner at a restaurant.", "우리는 식당에서 저녁을 먹었어요.", "장소"],
  ["station", "역", "명사", "The train station is near my house.", "기차역은 우리 집에서 가까워요.", "장소"],
  ["airport", "공항", "명사", "We arrived at the airport.", "우리는 공항에 도착했어요.", "장소"],
  ["church", "교회", "명사", "They go to church on Sunday.", "그들은 일요일에 교회에 가요.", "장소"],
  // 교통수단
  ["bus", "버스", "명사", "I go to school by bus.", "나는 버스를 타고 학교에 가요.", "교통수단"],
  ["car", "자동차", "명사", "My father drives a car.", "우리 아버지는 자동차를 운전하세요.", "교통수단"],
  ["train", "기차", "명사", "We travel by train.", "우리는 기차로 여행해요.", "교통수단"],
  ["airplane", "비행기", "명사", "We flew by airplane.", "우리는 비행기를 타고 갔어요.", "교통수단"],
  ["ship", "배", "명사", "The ship sails on the sea.", "배가 바다를 항해해요.", "교통수단"],
  ["bicycle", "자전거", "명사", "I ride my bicycle every day.", "나는 매일 자전거를 타요.", "교통수단"],
  ["subway", "지하철", "명사", "We take the subway to school.", "우리는 지하철을 타고 학교에 가요.", "교통수단"],
  ["taxi", "택시", "명사", "We took a taxi home.", "우리는 택시를 타고 집에 갔어요.", "교통수단"],
  ["truck", "트럭", "명사", "A big truck passed by.", "큰 트럭이 지나갔어요.", "교통수단"],
  ["motorcycle", "오토바이", "명사", "He rides a motorcycle.", "그는 오토바이를 타요.", "교통수단"],
  // 취미/운동
  ["soccer", "축구", "명사", "I play soccer with my friends.", "나는 친구들과 축구를 해요.", "취미/운동"],
  ["baseball", "야구", "명사", "He likes playing baseball.", "그는 야구하는 것을 좋아해요.", "취미/운동"],
  ["basketball", "농구", "명사", "We play basketball after school.", "우리는 방과 후에 농구를 해요.", "취미/운동"],
  ["swimming", "수영", "명사", "Swimming is good exercise.", "수영은 좋은 운동이에요.", "취미/운동"],
  ["dancing", "춤", "명사", "She is good at dancing.", "그녀는 춤을 잘 춰요.", "취미/운동"],
  ["singing", "노래하기", "명사", "Singing makes me happy.", "노래하는 것은 나를 행복하게 해요.", "취미/운동"],
  ["drawing", "그림 그리기", "명사", "Drawing is my hobby.", "그림 그리기는 내 취미예요.", "취미/운동"],
  ["reading", "독서", "명사", "Reading books is fun.", "책을 읽는 것은 재미있어요.", "취미/운동"],
  ["camping", "캠핑", "명사", "We went camping last weekend.", "우리는 지난 주말에 캠핑을 갔어요.", "취미/운동"],
  ["cooking", "요리", "명사", "My mother enjoys cooking.", "우리 엄마는 요리하는 것을 즐기세요.", "취미/운동"],
  // 감정
  ["angry", "화난", "형용사", "He looks angry.", "그는 화가 나 보여요.", "감정"],
  ["surprised", "놀란", "형용사", "I was surprised at the news.", "나는 그 소식에 놀랐어요.", "감정"],
  ["scared", "무서운, 겁먹은", "형용사", "The kid was scared of the dark.", "그 아이는 어둠을 무서워했어요.", "감정"],
  ["excited", "신난, 흥분한", "형용사", "We are excited about the trip.", "우리는 여행에 신나 있어요.", "감정"],
  ["tired", "피곤한", "형용사", "I am tired after school.", "나는 방과 후에 피곤해요.", "감정"],
  ["bored", "지루해하는", "형용사", "He looks bored.", "그는 지루해 보여요.", "감정"],
  ["worried", "걱정하는", "형용사", "She is worried about the test.", "그녀는 시험이 걱정돼요.", "감정"],
  ["glad", "기쁜", "형용사", "I am glad to see you.", "너를 만나서 기뻐.", "감정"],
  ["nervous", "긴장한", "형용사", "I feel nervous before the test.", "나는 시험 전에 긴장돼요.", "감정"],
  ["proud", "자랑스러운", "형용사", "My parents are proud of me.", "우리 부모님은 나를 자랑스러워하세요.", "감정"],
  // 일상동사
  ["wash", "씻다", "동사", "I wash my hands before eating.", "나는 밥 먹기 전에 손을 씻어요.", "일상동사"],
  ["brush", "닦다, 빗다", "동사", "I brush my teeth twice a day.", "나는 하루에 두 번 이를 닦아요.", "일상동사"],
  ["clean", "청소하다", "동사", "I clean my room every Saturday.", "나는 매주 토요일에 방을 청소해요.", "일상동사"],
  ["cook", "요리하다", "동사", "My father cooks dinner.", "우리 아버지는 저녁을 요리하세요.", "일상동사"],
  ["wake", "깨다, 일어나다", "동사", "I wake up at seven.", "나는 일곱 시에 일어나요.", "일상동사"],
  ["dress", "옷을 입다", "동사", "I dress myself in the morning.", "나는 아침에 스스로 옷을 입어요.", "일상동사"],
  ["study", "공부하다", "동사", "I study English every day.", "나는 매일 영어를 공부해요.", "일상동사"],
  ["help", "돕다", "동사", "I help my mom with chores.", "나는 엄마의 집안일을 도와요.", "일상동사"],
  ["buy", "사다", "동사", "I want to buy a new book.", "나는 새 책을 사고 싶어요.", "일상동사"],
  ["sell", "팔다", "동사", "The store sells fresh fruit.", "그 가게는 신선한 과일을 팔아요.", "일상동사"],
  // 형용사
  ["tall", "키가 큰", "형용사", "My brother is very tall.", "우리 오빠는 키가 아주 커요.", "형용사"],
  ["short", "짧은, 키가 작은", "형용사", "She has short hair.", "그녀는 짧은 머리를 가지고 있어요.", "형용사"],
  ["long", "긴", "형용사", "The river is very long.", "그 강은 아주 길어요.", "형용사"],
  ["fast", "빠른", "형용사", "The cheetah is very fast.", "치타는 매우 빨라요.", "형용사"],
  ["slow", "느린", "형용사", "The turtle is slow.", "거북이는 느려요.", "형용사"],
  ["heavy", "무거운", "형용사", "My bag is heavy.", "내 가방은 무거워요.", "형용사"],
  ["light", "가벼운", "형용사", "This box is light.", "이 상자는 가벼워요.", "형용사"],
  ["easy", "쉬운", "형용사", "This test is easy.", "이 시험은 쉬워요.", "형용사"],
  ["difficult", "어려운", "형용사", "Math homework is difficult.", "수학 숙제는 어려워요.", "형용사"],
  ["strong", "힘센, 강한", "형용사", "He is very strong.", "그는 아주 힘이 세요.", "형용사"],
  // 생활표현
  ["eleven", "열하나, 11", "수사", "I have eleven marbles.", "나는 구슬 열한 개가 있어요.", "생활표현"],
  ["twelve", "열둘, 12", "수사", "There are twelve months in a year.", "일 년은 열두 달이에요.", "생활표현"],
  ["twenty", "스물, 20", "수사", "My mother is thirty, I am ten... wait she is over twenty.", "우리 엄마는 스무 살이 넘었어요.", "생활표현"],
  ["thirty", "서른, 30", "수사", "The bus comes every thirty minutes.", "버스는 삼십 분마다 와요.", "생활표현"],
  ["hundred", "백, 100", "수사", "I have one hundred stickers.", "나는 스티커가 백 개 있어요.", "생활표현"],
  ["cousin", "사촌", "명사", "My cousin visits us every summer.", "내 사촌은 매년 여름 우리를 방문해요.", "생활표현"],
  ["neighbor", "이웃", "명사", "My neighbor is very kind.", "우리 이웃은 아주 친절해요.", "생활표현"],
  ["classmate", "반 친구", "명사", "He is my classmate.", "그는 내 반 친구예요.", "생활표현"],
  ["address", "주소", "명사", "What is your address?", "네 주소가 뭐야?", "생활표현"],
  ["phone", "전화기", "명사", "May I use your phone?", "네 전화기를 써도 될까?", "생활표현"],
];

const GRADE_5: WordTuple[] = [
  // 직업
  ["doctor", "의사", "명사", "The doctor helps sick people.", "의사는 아픈 사람들을 도와줘요.", "직업"],
  ["nurse", "간호사", "명사", "The nurse works at the hospital.", "간호사는 병원에서 일해요.", "직업"],
  ["police officer", "경찰관", "명사", "The police officer keeps us safe.", "경찰관은 우리를 안전하게 지켜줘요.", "직업"],
  ["firefighter", "소방관", "명사", "The firefighter puts out fires.", "소방관은 불을 꺼요.", "직업"],
  ["vet", "수의사", "명사", "The vet takes care of sick animals.", "수의사는 아픈 동물들을 돌봐줘요.", "직업"],
  ["farmer", "농부", "명사", "The farmer grows rice.", "농부는 쌀을 길러요.", "직업"],
  ["scientist", "과학자", "명사", "The scientist studies stars.", "과학자는 별을 연구해요.", "직업"],
  ["artist", "예술가, 화가", "명사", "The artist paints beautiful pictures.", "그 예술가는 아름다운 그림을 그려요.", "직업"],
  ["singer", "가수", "명사", "My favorite singer has a great voice.", "내가 가장 좋아하는 가수는 목소리가 좋아요.", "직업"],
  ["actor", "배우", "명사", "The actor is famous.", "그 배우는 유명해요.", "직업"],
  // 자연
  ["mountain", "산", "명사", "We climbed the mountain.", "우리는 산에 올랐어요.", "자연"],
  ["river", "강", "명사", "The river flows to the sea.", "강은 바다로 흘러가요.", "자연"],
  ["sea", "바다", "명사", "We swim in the sea.", "우리는 바다에서 수영해요.", "자연"],
  ["sky", "하늘", "명사", "The sky is blue and clear.", "하늘이 파랗고 맑아요.", "자연"],
  ["star", "별", "명사", "I can see many stars at night.", "밤에는 많은 별을 볼 수 있어요.", "자연"],
  ["moon", "달", "명사", "The moon is bright tonight.", "오늘 밤 달이 밝아요.", "자연"],
  ["sun", "태양, 해", "명사", "The sun rises in the east.", "해는 동쪽에서 떠요.", "자연"],
  ["tree", "나무", "명사", "Birds live in the tree.", "새들이 나무에서 살아요.", "자연"],
  ["flower", "꽃", "명사", "The flower smells nice.", "그 꽃은 좋은 향이 나요.", "자연"],
  ["forest", "숲", "명사", "Many animals live in the forest.", "많은 동물들이 숲에서 살아요.", "자연"],
  // 형용사
  ["important", "중요한", "형용사", "Family is important to me.", "가족은 나에게 중요해요.", "형용사"],
  ["famous", "유명한", "형용사", "She is a famous singer.", "그녀는 유명한 가수예요.", "형용사"],
  ["popular", "인기 있는", "형용사", "This game is very popular.", "이 게임은 아주 인기가 많아요.", "형용사"],
  ["dangerous", "위험한", "형용사", "It is dangerous to swim alone.", "혼자 수영하는 것은 위험해요.", "형용사"],
  ["interesting", "흥미로운", "형용사", "This book is interesting.", "이 책은 흥미로워요.", "형용사"],
  ["boring", "지루한", "형용사", "The movie was boring.", "그 영화는 지루했어요.", "형용사"],
  ["exciting", "흥미진진한", "형용사", "The game was exciting.", "그 경기는 흥미진진했어요.", "형용사"],
  ["useful", "유용한", "형용사", "This tool is very useful.", "이 도구는 아주 유용해요.", "형용사"],
  ["special", "특별한", "형용사", "Today is a special day.", "오늘은 특별한 날이에요.", "형용사"],
  ["wonderful", "멋진, 훌륭한", "형용사", "We had a wonderful time.", "우리는 멋진 시간을 보냈어요.", "형용사"],
  // 부사
  ["always", "항상", "부사", "I always brush my teeth.", "나는 항상 이를 닦아요.", "부사"],
  ["sometimes", "가끔", "부사", "I sometimes watch TV.", "나는 가끔 TV를 봐요.", "부사"],
  ["often", "자주", "부사", "We often play together.", "우리는 자주 함께 놀아요.", "부사"],
  ["usually", "보통", "부사", "I usually walk to school.", "나는 보통 걸어서 학교에 가요.", "부사"],
  ["never", "결코 ~않다", "부사", "I never lie to my friends.", "나는 친구들에게 절대 거짓말하지 않아요.", "부사"],
  ["quickly", "빨리, 신속하게", "부사", "He finished his lunch quickly.", "그는 점심을 빨리 먹었어요.", "부사"],
  ["slowly", "천천히", "부사", "Please walk slowly.", "천천히 걸어주세요.", "부사"],
  ["carefully", "조심스럽게", "부사", "She crossed the street carefully.", "그녀는 조심스럽게 길을 건넜어요.", "부사"],
  ["loudly", "크게, 시끄럽게", "부사", "He spoke loudly.", "그는 크게 말했어요.", "부사"],
  ["quietly", "조용히", "부사", "Please read quietly.", "조용히 읽어주세요.", "부사"],
  // 여행
  ["trip", "여행", "명사", "We are going on a trip.", "우리는 여행을 가요.", "여행"],
  ["vacation", "방학, 휴가", "명사", "I visited my grandma during vacation.", "나는 방학 동안 할머니를 방문했어요.", "여행"],
  ["hotel", "호텔", "명사", "We stayed at a nice hotel.", "우리는 좋은 호텔에서 묵었어요.", "여행"],
  ["ticket", "표, 티켓", "명사", "I bought a train ticket.", "나는 기차표를 샀어요.", "여행"],
  ["passport", "여권", "명사", "Don't forget your passport.", "여권을 잊지 마세요.", "여행"],
  ["map", "지도", "명사", "We used a map to find the way.", "우리는 길을 찾기 위해 지도를 사용했어요.", "여행"],
  ["camera", "카메라", "명사", "I took pictures with my camera.", "나는 카메라로 사진을 찍었어요.", "여행"],
  ["suitcase", "여행 가방", "명사", "I packed my suitcase.", "나는 여행 가방을 쌌어요.", "여행"],
  ["guide", "안내자, 가이드", "명사", "The guide showed us around.", "가이드가 우리를 안내해 주었어요.", "여행"],
  ["souvenir", "기념품", "명사", "I bought a souvenir for my friend.", "나는 친구에게 줄 기념품을 샀어요.", "여행"],
  // 쇼핑
  ["money", "돈", "명사", "I saved my money.", "나는 돈을 저축했어요.", "쇼핑"],
  ["price", "가격", "명사", "The price is too high.", "가격이 너무 비싸요.", "쇼핑"],
  ["cheap", "값싼", "형용사", "This toy is cheap.", "이 장난감은 저렴해요.", "쇼핑"],
  ["expensive", "비싼", "형용사", "That watch is expensive.", "그 시계는 비싸요.", "쇼핑"],
  ["discount", "할인", "명사", "We got a discount on shoes.", "우리는 신발을 할인받았어요.", "쇼핑"],
  ["coin", "동전", "명사", "I found a coin on the street.", "나는 길에서 동전을 발견했어요.", "쇼핑"],
  ["bill", "지폐, 계산서", "명사", "He paid with a bill.", "그는 지폐로 계산했어요.", "쇼핑"],
  ["wallet", "지갑", "명사", "My wallet is in my bag.", "내 지갑은 가방 안에 있어요.", "쇼핑"],
  ["receipt", "영수증", "명사", "Keep the receipt.", "영수증을 보관하세요.", "쇼핑"],
  ["customer", "손님, 고객", "명사", "The store has many customers.", "그 가게는 손님이 많아요.", "쇼핑"],
  // 건강
  ["sick", "아픈", "형용사", "I feel sick today.", "나는 오늘 몸이 아파요.", "건강"],
  ["healthy", "건강한", "형용사", "Eating vegetables is healthy.", "채소를 먹는 것은 건강에 좋아요.", "건강"],
  ["medicine", "약", "명사", "Take this medicine after meals.", "식후에 이 약을 드세요.", "건강"],
  ["exercise", "운동", "명사", "Exercise every day.", "매일 운동하세요.", "건강"],
  ["rest", "휴식", "명사", "You need some rest.", "너는 휴식이 필요해.", "건강"],
  ["pain", "통증", "명사", "I have a pain in my leg.", "다리에 통증이 있어요.", "건강"],
  ["fever", "열", "명사", "He has a high fever.", "그는 고열이 있어요.", "건강"],
  ["cough", "기침", "명사", "She has a bad cough.", "그녀는 기침이 심해요.", "건강"],
  ["dentist", "치과 의사", "명사", "I go to the dentist twice a year.", "나는 일 년에 두 번 치과에 가요.", "건강"],
  ["checkup", "건강 검진", "명사", "I had a checkup last week.", "나는 지난주에 건강 검진을 받았어요.", "건강"],
  // 동사확장
  ["decide", "결정하다", "동사", "I decided to study harder.", "나는 더 열심히 공부하기로 결정했어요.", "동사확장"],
  ["believe", "믿다", "동사", "I believe you.", "나는 너를 믿어.", "동사확장"],
  ["understand", "이해하다", "동사", "I understand the problem now.", "나는 이제 그 문제를 이해해요.", "동사확장"],
  ["remember", "기억하다", "동사", "I remember your name.", "나는 네 이름을 기억해.", "동사확장"],
  ["forget", "잊다", "동사", "Don't forget your homework.", "숙제를 잊지 마세요.", "동사확장"],
  ["invite", "초대하다", "동사", "I invited my friends to my party.", "나는 파티에 친구들을 초대했어요.", "동사확장"],
  ["agree", "동의하다", "동사", "I agree with you.", "나는 너에게 동의해.", "동사확장"],
  ["borrow", "빌리다", "동사", "Can I borrow your pencil?", "네 연필 좀 빌릴 수 있을까?", "동사확장"],
  ["lend", "빌려주다", "동사", "Can you lend me your book?", "네 책 좀 빌려줄 수 있어?", "동사확장"],
  ["promise", "약속하다", "동사", "I promise to help you.", "너를 돕겠다고 약속할게.", "동사확장"],
  // 문화
  ["festival", "축제", "명사", "We enjoyed the festival.", "우리는 축제를 즐겼어요.", "문화"],
  ["holiday", "휴일, 명절", "명사", "Chuseok is a Korean holiday.", "추석은 한국의 명절이에요.", "문화"],
  ["tradition", "전통", "명사", "This is an old tradition.", "이것은 오래된 전통이에요.", "문화"],
  ["custom", "관습, 풍습", "명사", "Every country has its own customs.", "모든 나라에는 저마다의 풍습이 있어요.", "문화"],
  ["country", "나라, 국가", "명사", "Korea is a beautiful country.", "한국은 아름다운 나라예요.", "문화"],
  ["language", "언어", "명사", "English is a global language.", "영어는 세계적인 언어예요.", "문화"],
  ["culture", "문화", "명사", "I want to learn about other cultures.", "나는 다른 문화에 대해 배우고 싶어요.", "문화"],
  ["world", "세계", "명사", "There are many countries in the world.", "세계에는 많은 나라가 있어요.", "문화"],
  ["history", "역사", "명사", "I like learning history.", "나는 역사를 배우는 것을 좋아해요.", "문화"],
  ["celebrate", "축하하다", "동사", "We celebrate his birthday every year.", "우리는 매년 그의 생일을 축하해요.", "문화"],
  // 추상명사 기초
  ["idea", "생각, 아이디어", "명사", "That's a good idea.", "그거 좋은 생각이야.", "추상명사 기초"],
  ["plan", "계획", "명사", "What is your plan for today?", "오늘 계획이 뭐야?", "추상명사 기초"],
  ["problem", "문제", "명사", "We solved the problem together.", "우리는 함께 그 문제를 해결했어요.", "추상명사 기초"],
  ["solution", "해결책", "명사", "We found a good solution.", "우리는 좋은 해결책을 찾았어요.", "추상명사 기초"],
  ["reason", "이유", "명사", "Tell me the reason.", "이유를 말해줘.", "추상명사 기초"],
  ["chance", "기회", "명사", "Give me a chance.", "나에게 기회를 줘.", "추상명사 기초"],
  ["effort", "노력", "명사", "He made a great effort.", "그는 큰 노력을 기울였어요.", "추상명사 기초"],
  ["goal", "목표", "명사", "My goal is to be a doctor.", "내 목표는 의사가 되는 거예요.", "추상명사 기초"],
  ["dream", "꿈", "명사", "I had a strange dream.", "나는 이상한 꿈을 꿨어요.", "추상명사 기초"],
  ["future", "미래", "명사", "I often think about my future.", "나는 자주 내 미래에 대해 생각해요.", "추상명사 기초"],
];

const GRADE_6: WordTuple[] = [
  // 사회
  ["society", "사회", "명사", "We live in a modern society.", "우리는 현대 사회에서 살아요.", "사회"],
  ["citizen", "시민", "명사", "Every citizen has rights.", "모든 시민은 권리를 가지고 있어요.", "사회"],
  ["community", "공동체, 지역 사회", "명사", "We help our community.", "우리는 지역 사회를 도와요.", "사회"],
  ["government", "정부", "명사", "The government makes laws.", "정부는 법을 만들어요.", "사회"],
  ["law", "법", "명사", "We must follow the law.", "우리는 법을 따라야 해요.", "사회"],
  ["vote", "투표하다", "동사", "Citizens vote for their leaders.", "시민들은 지도자를 뽑기 위해 투표해요.", "사회"],
  ["right", "권리", "명사", "Children have the right to education.", "어린이는 교육받을 권리가 있어요.", "사회"],
  ["duty", "의무", "명사", "It is our duty to help others.", "다른 사람을 돕는 것은 우리의 의무예요.", "사회"],
  ["freedom", "자유", "명사", "Freedom is important to everyone.", "자유는 모두에게 중요해요.", "사회"],
  ["equality", "평등", "명사", "We believe in equality.", "우리는 평등을 믿어요.", "사회"],
  // 환경
  ["environment", "환경", "명사", "We must protect the environment.", "우리는 환경을 보호해야 해요.", "환경"],
  ["pollution", "오염", "명사", "Air pollution is a big problem.", "대기 오염은 큰 문제예요.", "환경"],
  ["recycle", "재활용하다", "동사", "We should recycle paper and cans.", "우리는 종이와 캔을 재활용해야 해요.", "환경"],
  ["energy", "에너지", "명사", "We need to save energy.", "우리는 에너지를 절약해야 해요.", "환경"],
  ["resource", "자원", "명사", "Water is a precious resource.", "물은 소중한 자원이에요.", "환경"],
  ["waste", "쓰레기, 낭비하다", "명사", "Don't waste food.", "음식을 낭비하지 마세요.", "환경"],
  ["climate", "기후", "명사", "The climate is changing.", "기후가 변하고 있어요.", "환경"],
  ["earth", "지구", "명사", "We should take care of the earth.", "우리는 지구를 소중히 여겨야 해요.", "환경"],
  ["planet", "행성", "명사", "Earth is a beautiful planet.", "지구는 아름다운 행성이에요.", "환경"],
  ["protect", "보호하다", "동사", "We must protect nature.", "우리는 자연을 보호해야 해요.", "환경"],
  // 과학
  ["experiment", "실험", "명사", "We did a science experiment.", "우리는 과학 실험을 했어요.", "과학"],
  ["observe", "관찰하다", "동사", "Scientists observe the stars.", "과학자들은 별을 관찰해요.", "과학"],
  ["discover", "발견하다", "동사", "He discovered a new planet.", "그는 새로운 행성을 발견했어요.", "과학"],
  ["invent", "발명하다", "동사", "She invented a useful machine.", "그녀는 유용한 기계를 발명했어요.", "과학"],
  ["technology", "기술", "명사", "Technology changes our lives.", "기술은 우리 삶을 변화시켜요.", "과학"],
  ["machine", "기계", "명사", "This machine washes clothes.", "이 기계는 옷을 세탁해요.", "과학"],
  ["robot", "로봇", "명사", "The robot can clean the house.", "그 로봇은 집을 청소할 수 있어요.", "과학"],
  ["space", "우주", "명사", "Astronauts travel in space.", "우주 비행사는 우주를 여행해요.", "과학"],
  ["universe", "우주, 은하계", "명사", "The universe is very large.", "우주는 매우 커요.", "과학"],
  ["gravity", "중력", "명사", "Gravity pulls things down.", "중력은 물체를 아래로 끌어당겨요.", "과학"],
  // 추상명사
  ["courage", "용기", "명사", "It takes courage to try new things.", "새로운 것을 시도하려면 용기가 필요해요.", "추상명사"],
  ["honesty", "정직", "명사", "Honesty is the best policy.", "정직이 최선의 방책이에요.", "추상명사"],
  ["kindness", "친절", "명사", "Thank you for your kindness.", "당신의 친절에 감사해요.", "추상명사"],
  ["patience", "인내심", "명사", "Learning takes patience.", "배우는 것은 인내심이 필요해요.", "추상명사"],
  ["wisdom", "지혜", "명사", "My grandfather has great wisdom.", "우리 할아버지는 큰 지혜를 가지고 계세요.", "추상명사"],
  ["respect", "존중", "명사", "We should respect others.", "우리는 다른 사람을 존중해야 해요.", "추상명사"],
  ["trust", "신뢰", "명사", "Trust is important in friendship.", "신뢰는 우정에서 중요해요.", "추상명사"],
  ["hope", "희망", "명사", "Never lose hope.", "희망을 절대 잃지 마세요.", "추상명사"],
  ["peace", "평화", "명사", "We want world peace.", "우리는 세계 평화를 원해요.", "추상명사"],
  ["justice", "정의", "명사", "The judge believes in justice.", "그 판사는 정의를 믿어요.", "추상명사"],
  // 진로
  ["engineer", "기술자, 엔지니어", "명사", "My uncle is an engineer.", "우리 삼촌은 엔지니어예요.", "진로"],
  ["designer", "디자이너", "명사", "She wants to be a fashion designer.", "그녀는 패션 디자이너가 되고 싶어해요.", "진로"],
  ["journalist", "기자", "명사", "The journalist writes news articles.", "그 기자는 뉴스 기사를 써요.", "진로"],
  ["lawyer", "변호사", "명사", "My aunt is a lawyer.", "우리 이모는 변호사예요.", "진로"],
  ["pilot", "조종사", "명사", "The pilot flies the airplane.", "조종사는 비행기를 조종해요.", "진로"],
  ["chef", "요리사, 셰프", "명사", "The chef cooks amazing food.", "그 셰프는 놀라운 음식을 요리해요.", "진로"],
  ["architect", "건축가", "명사", "The architect designed this building.", "그 건축가는 이 건물을 설계했어요.", "진로"],
  ["programmer", "프로그래머", "명사", "A programmer writes computer code.", "프로그래머는 컴퓨터 코드를 작성해요.", "진로"],
  ["president", "대통령, 회장", "명사", "The president gave a speech.", "대통령이 연설을 했어요.", "진로"],
  ["volunteer", "자원봉사자", "명사", "I want to be a volunteer.", "나는 자원봉사자가 되고 싶어요.", "진로"],
  // 기술
  ["computer", "컴퓨터", "명사", "I do my homework on the computer.", "나는 컴퓨터로 숙제를 해요.", "기술"],
  ["internet", "인터넷", "명사", "I search for information on the internet.", "나는 인터넷에서 정보를 검색해요.", "기술"],
  ["smartphone", "스마트폰", "명사", "Many people use a smartphone.", "많은 사람들이 스마트폰을 사용해요.", "기술"],
  ["website", "웹사이트", "명사", "This website is useful.", "이 웹사이트는 유용해요.", "기술"],
  ["email", "이메일", "명사", "I sent an email to my teacher.", "나는 선생님께 이메일을 보냈어요.", "기술"],
  ["software", "소프트웨어", "명사", "This software helps me study.", "이 소프트웨어는 공부에 도움이 돼요.", "기술"],
  ["keyboard", "키보드", "명사", "I type on the keyboard.", "나는 키보드로 타자를 쳐요.", "기술"],
  ["screen", "화면", "명사", "The screen is very bright.", "화면이 아주 밝아요.", "기술"],
  ["download", "다운로드하다", "동사", "I downloaded a new app.", "나는 새 앱을 다운로드했어요.", "기술"],
  ["upload", "업로드하다", "동사", "She uploaded her photos.", "그녀는 사진을 업로드했어요.", "기술"],
  // 성격
  ["honest", "정직한", "형용사", "He is an honest boy.", "그는 정직한 소년이에요.", "성격"],
  ["brave", "용감한", "형용사", "The firefighter is brave.", "그 소방관은 용감해요.", "성격"],
  ["kind", "친절한", "형용사", "She is kind to everyone.", "그녀는 모두에게 친절해요.", "성격"],
  ["polite", "예의 바른", "형용사", "He is always polite.", "그는 항상 예의 바르게 행동해요.", "성격"],
  ["careful", "조심스러운", "형용사", "Be careful when you cross the road.", "길을 건널 때 조심하세요.", "성격"],
  ["curious", "호기심 많은", "형용사", "My sister is curious about everything.", "내 여동생은 모든 것에 호기심이 많아요.", "성격"],
  ["confident", "자신감 있는", "형용사", "She spoke with confident voice.", "그녀는 자신감 있는 목소리로 말했어요.", "성격"],
  ["humble", "겸손한", "형용사", "The champion was humble.", "그 챔피언은 겸손했어요.", "성격"],
  ["patient", "참을성 있는", "형용사", "You need to be patient.", "너는 참을성이 있어야 해.", "성격"],
  ["generous", "관대한, 후한", "형용사", "He is generous with his time.", "그는 시간을 아끼지 않고 후하게 써요.", "성격"],
  // 동사확장2
  ["achieve", "이루다, 성취하다", "동사", "She achieved her goal.", "그녀는 목표를 이루었어요.", "동사확장2"],
  ["improve", "향상시키다", "동사", "I want to improve my English.", "나는 영어 실력을 향상시키고 싶어요.", "동사확장2"],
  ["develop", "발전시키다, 개발하다", "동사", "The city is developing quickly.", "그 도시는 빠르게 발전하고 있어요.", "동사확장2"],
  ["communicate", "의사소통하다", "동사", "We communicate through letters.", "우리는 편지로 의사소통해요.", "동사확장2"],
  ["cooperate", "협력하다", "동사", "We should cooperate with each other.", "우리는 서로 협력해야 해요.", "동사확장2"],
  ["solve", "해결하다", "동사", "Let's solve this problem together.", "이 문제를 함께 해결해봅시다.", "동사확장2"],
  ["create", "창조하다, 만들다", "동사", "She created a new game.", "그녀는 새로운 게임을 만들었어요.", "동사확장2"],
  ["imagine", "상상하다", "동사", "Imagine a world without cars.", "자동차가 없는 세상을 상상해보세요.", "동사확장2"],
  ["explain", "설명하다", "동사", "Can you explain this problem?", "이 문제를 설명해줄 수 있어?", "동사확장2"],
  ["compare", "비교하다", "동사", "Let's compare the two pictures.", "이 두 그림을 비교해봅시다.", "동사확장2"],
  // 표현/개념
  ["opinion", "의견", "명사", "What is your opinion?", "네 의견은 뭐야?", "표현/개념"],
  ["example", "예시, 예", "명사", "Can you give me an example?", "예시를 하나 들어줄 수 있어?", "표현/개념"],
  ["information", "정보", "명사", "This book has useful information.", "이 책에는 유용한 정보가 있어요.", "표현/개념"],
  ["fact", "사실", "명사", "That is an interesting fact.", "그것은 흥미로운 사실이에요.", "표현/개념"],
  ["difference", "차이", "명사", "What is the difference between these two?", "이 둘의 차이가 뭐야?", "표현/개념"],
  ["similarity", "유사점", "명사", "There is a similarity between them.", "그것들 사이에는 유사점이 있어요.", "표현/개념"],
  ["advantage", "장점", "명사", "There are many advantages to reading.", "독서에는 많은 장점이 있어요.", "표현/개념"],
  ["disadvantage", "단점", "명사", "Every choice has a disadvantage.", "모든 선택에는 단점이 있어요.", "표현/개념"],
  ["experience", "경험", "명사", "It was a great experience.", "그것은 좋은 경험이었어요.", "표현/개념"],
  ["opportunity", "기회", "명사", "This is a good opportunity.", "이것은 좋은 기회예요.", "표현/개념"],
  // 사회/과학 확장
  ["population", "인구", "명사", "The population of the city is growing.", "그 도시의 인구가 늘어나고 있어요.", "사회/과학 확장"],
  ["temperature", "온도, 기온", "명사", "The temperature is rising.", "기온이 오르고 있어요.", "사회/과학 확장"],
  ["distance", "거리", "명사", "The distance is too far to walk.", "그 거리는 걷기에 너무 멀어요.", "사회/과학 확장"],
  ["direction", "방향", "명사", "We walked in the wrong direction.", "우리는 잘못된 방향으로 걸었어요.", "사회/과학 확장"],
  ["condition", "상태, 조건", "명사", "The car is in good condition.", "그 차는 상태가 좋아요.", "사회/과학 확장"],
  ["situation", "상황", "명사", "This is a difficult situation.", "이것은 어려운 상황이에요.", "사회/과학 확장"],
  ["purpose", "목적", "명사", "What is the purpose of this meeting?", "이 회의의 목적이 뭐예요?", "사회/과학 확장"],
  ["method", "방법", "명사", "This is a good method to learn words.", "이것은 단어를 배우는 좋은 방법이에요.", "사회/과학 확장"],
  ["result", "결과", "명사", "The result of the test was good.", "시험 결과가 좋았어요.", "사회/과학 확장"],
  ["process", "과정", "명사", "Learning is a slow process.", "배움은 느린 과정이에요.", "사회/과학 확장"],
];

function toSeeds(rows: WordTuple[], grade: number): WordSeed[] {
  return rows.map(([text, meaning, partOfSpeech, exampleEn, exampleKo, category]) => ({
    text,
    meaning,
    partOfSpeech,
    exampleEn,
    exampleKo,
    grade,
    category,
  }));
}

export const WORD_SEEDS: WordSeed[] = [
  ...toSeeds(GRADE_3, 3),
  ...toSeeds(GRADE_4, 4),
  ...toSeeds(GRADE_5, 5),
  ...toSeeds(GRADE_6, 6),
];
